"""empty message

Revision ID: 0c9cbfebb39d
Revises: 46dd3fa34786
Create Date: 2022-04-21 15:58:19.727149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9cbfebb39d'
down_revision = '46dd3fa34786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clv_calculation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_transaction', sa.Integer(), nullable=True),
    sa.Column('total_unit', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('average_order_value', sa.Float(), nullable=True),
    sa.Column('purchase_frequency', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('customer_value', sa.Float(), nullable=True),
    sa.Column('customer_lifetime_value', sa.Float(), nullable=True),
    sa.Column('scaled_cltv', sa.Float(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cltvc_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_customers_index')
        batch_op.create_foreign_key("fl_clv_calculation", 'clv_calculation', ['cltvc_id'], ['id'])
        batch_op.create_foreign_key("fk_rfm_segments", 'rfm_segments', ['rfm_id'], ['id'])
        batch_op.drop_column('index')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_order_items_id')
        batch_op.create_foreign_key("fk_products", 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key("fk_orders", 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('rfm_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_rfm_segments_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rfm_segments', schema=None) as batch_op:
        batch_op.create_index('ix_rfm_segments_id', ['id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_order_items_id', ['id'], unique=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_customers_index', ['index'], unique=False)
        batch_op.drop_column('cltvc_id')

    op.drop_table('clv_calculation')
    # ### end Alembic commands ###
