"""empty message

Revision ID: 229c8a681460
Revises: ba5336d3ab89
Create Date: 2022-04-23 11:22:31.798769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229c8a681460'
down_revision = 'ba5336d3ab89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clv_calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_lifetime_value', sa.Float(), nullable=True))
        batch_op.drop_index('ix_clv_calculation_id')
        batch_op.drop_column('cltv')

    with op.batch_alter_table('clv_pred', schema=None) as batch_op:
        batch_op.drop_index('ix_clv_pred_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_created_date')
        batch_op.create_foreign_key("fk_clv_pred", 'clv_pred', ['cltvp_id'], ['id'])
        batch_op.create_foreign_key("fk_clv_calculation", 'clv_calculation', ['cltvc_id'], ['id'])
        batch_op.create_foreign_key("fk_rfm_segments", 'rfm_segments', ['rfm_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_order_items_id')
        batch_op.create_foreign_key("fk_orders", 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key("fk_products", 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_order_items_id', ['id'], unique=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_customers_created_date', ['created_date'], unique=False)

    with op.batch_alter_table('clv_pred', schema=None) as batch_op:
        batch_op.create_index('ix_clv_pred_id', ['id'], unique=False)

    with op.batch_alter_table('clv_calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cltv', sa.REAL(), nullable=True))
        batch_op.create_index('ix_clv_calculation_id', ['id'], unique=False)
        batch_op.drop_column('customer_lifetime_value')

    # ### end Alembic commands ###
