"""empty message

Revision ID: 402de1932184
Revises: e0402d368e74
Create Date: 2022-04-18 17:20:29.306825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402de1932184'
down_revision = 'e0402d368e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfm_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('recency', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('monetary', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.String(), nullable=True),
    sa.Column('freqeuncy_score', sa.String(), nullable=True),
    sa.Column('monetary_score', sa.String(), nullable=True),
    sa.Column('rfm_score', sa.String(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfm_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_rfm_segments", 'rfm_segments', ['rfm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rfm_id')

    op.drop_table('rfm_segments')
    # ### end Alembic commands ###
