"""empty message

Revision ID: 71d3806e7a83
Revises: a631b82ace30
Create Date: 2022-04-14 21:06:02.353947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d3806e7a83'
down_revision = 'a631b82ace30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedents', sa.String(length=500), nullable=True),
    sa.Column('consequents', sa.String(length=500), nullable=True),
    sa.Column('antecedent_support', sa.Float(), nullable=True),
    sa.Column('consequent_support', sa.Float(), nullable=True),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=True),
    sa.Column('conviction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    # ### end Alembic commands ###
