"""empty message

Revision ID: ba5336d3ab89
Revises: 0c9cbfebb39d
Create Date: 2022-04-21 16:34:58.215361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5336d3ab89'
down_revision = '0c9cbfebb39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clv_pred',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('recency', sa.Float(), nullable=True),
    sa.Column('T', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('monetary', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clv_calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_lifetime_value', sa.Float(), nullable=True))
        batch_op.drop_index('ix_clv_calculation_id')
        batch_op.drop_column('cltv')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cltvp_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_customers_index')
        batch_op.create_foreign_key("fk_clv_calculation", 'clv_calculation', ['cltvc_id'], ['id'])
        batch_op.create_foreign_key("fk_clv_pred", 'clv_pred', ['cltvp_id'], ['id'])
        batch_op.create_foreign_key("fk_rfm_segments", 'rfm_segments', ['rfm_id'], ['id'])
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_customers_index', ['index'], unique=False)
        batch_op.drop_column('cltvp_id')

    with op.batch_alter_table('clv_calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cltv', sa.REAL(), nullable=True))
        batch_op.create_index('ix_clv_calculation_id', ['id'], unique=False)
        batch_op.drop_column('customer_lifetime_value')

    op.drop_table('clv_pred')
    # ### end Alembic commands ###
