"""empty message

Revision ID: d8ffff06307e
Revises: fd11bb9aab67
Create Date: 2022-04-03 17:18:07.905406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ffff06307e'
down_revision = 'fd11bb9aab67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
