"""empty message

Revision ID: e512110855c0
Revises: 6e38f400a048
Create Date: 2022-04-17 22:44:06.965049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e512110855c0'
down_revision = '6e38f400a048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_product_id", 'products', ['product_id'], ['id'])
        batch_op.create_primary_key("pk_order_items", 'order_items', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='primarykey')

    # ### end Alembic commands ###
